-- Squashed Postgres schema: the final state of all 49 SQLite migrations
-- (v49), mapped to Postgres types.
--
-- Type mapping (plan-190):
--   INTEGER PK AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   singleton PK              -> BIGINT PRIMARY KEY CHECK (id = 1)
--   TEXT ISO timestamps       -> TIMESTAMPTZ NOT NULL DEFAULT now() (nullable where SQLite had no NOT NULL)
--   REAL                      -> DOUBLE PRECISION
--   int-bools                 -> BOOLEAN
--   JSON                      -> TEXT
--   every SQLite FK           -> FOREIGN KEY via REFERENCES clause
--
-- Do NOT create _sqlx_migrations (sqlx manages it).

-- model_configs must exist first: it is the FK target of
-- model_pulls / model_files / model_aliases.
CREATE TABLE model_configs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id       TEXT NOT NULL UNIQUE,
    display_name  TEXT,
    backend       TEXT NOT NULL DEFAULT 'llama_cpp',
    gpu_variant   TEXT,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    selected_quant  TEXT,
    selected_mmproj TEXT,
    context_length  BIGINT,
    num_parallel    BIGINT DEFAULT 0 CHECK (num_parallel >= 0),
    kv_unified      BOOLEAN NOT NULL DEFAULT FALSE,
    gpu_layers      BIGINT,
    cache_type_k    TEXT,
    cache_type_v    TEXT,
    port            BIGINT,
    args            TEXT,
    sampling        TEXT,
    modalities      TEXT,
    profile         TEXT,
    api_name        TEXT,
    health_check    TEXT,
    hf_format       TEXT,
    hf_base_model   TEXT,
    hf_pipeline_tag TEXT,
    hf_total_params TEXT,
    hf_active_params TEXT,
    hf_architecture_type TEXT,
    hf_context_length BIGINT,
    hf_num_layers   BIGINT,
    hf_last_modified TEXT,
    spec_decoding   TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    selected_mtp_model TEXT,
    gpu_device TEXT,
    n_batch BIGINT,
    n_ubatch BIGINT,
    vllm_config TEXT,
    backend_id TEXT,
    provider_name TEXT,
    reasoning_levels TEXT
);

CREATE TABLE model_pulls (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id   BIGINT NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
    repo_id    TEXT NOT NULL,
    commit_sha TEXT NOT NULL,
    pulled_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE model_files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id      BIGINT NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
    repo_id       TEXT NOT NULL,
    filename      TEXT NOT NULL,
    quant         TEXT,
    lfs_oid       TEXT,
    size_bytes    BIGINT,
    pulled_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_verified_at   TIMESTAMPTZ,
    verified_ok       BOOLEAN,
    verify_error      TEXT,
    kind          TEXT NOT NULL DEFAULT 'model'
);

CREATE TABLE model_aliases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    model_id    BIGINT NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
    description TEXT,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE active_models (
    server_name   TEXT PRIMARY KEY,
    model_name    TEXT NOT NULL,
    backend       TEXT NOT NULL,
    pid           BIGINT NOT NULL,
    port          BIGINT NOT NULL,
    backend_url   TEXT NOT NULL,
    loaded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_accessed TIMESTAMPTZ NOT NULL DEFAULT now(),
    backend_id    TEXT
);

CREATE TABLE api_keys (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL DEFAULT '',
    key_prefix   TEXT NOT NULL,
    key_hash     TEXT NOT NULL UNIQUE,
    scopes       TEXT NOT NULL,
    created_by   TEXT NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ
);

CREATE TABLE app_compaction (
    id                  BIGINT PRIMARY KEY CHECK (id = 1),
    enabled             BOOLEAN NOT NULL DEFAULT FALSE,
    server_path         TEXT,
    device              TEXT NOT NULL DEFAULT 'cpu',
    port                BIGINT,
    request_timeout_ms  BIGINT NOT NULL DEFAULT 30000
);

CREATE TABLE app_general (
    id                       BIGINT PRIMARY KEY CHECK (id = 1),
    log_level                TEXT NOT NULL DEFAULT 'info',
    models_dir               TEXT,
    logs_dir                 TEXT,
    hf_token                 TEXT,
    update_check_interval    BIGINT NOT NULL DEFAULT 12
);

CREATE TABLE app_langfuse (
    id                      BIGINT PRIMARY KEY CHECK (id = 1),
    enabled                 BOOLEAN NOT NULL DEFAULT FALSE,
    public_key              TEXT NOT NULL DEFAULT '',
    secret_key              TEXT NOT NULL DEFAULT '',
    host                    TEXT NOT NULL DEFAULT 'https://cloud.langfuse.com',
    environment             TEXT NOT NULL DEFAULT 'default',
    capture_input           BOOLEAN NOT NULL DEFAULT TRUE,
    capture_output          BOOLEAN NOT NULL DEFAULT TRUE,
    capture_streaming       BOOLEAN NOT NULL DEFAULT TRUE,
    telemetry_max_bytes     BIGINT NOT NULL DEFAULT 1048576,
    electricity_price_per_kwh DOUBLE PRECISION NOT NULL DEFAULT 0.0
);

CREATE TABLE app_lifecycle (
    id                        BIGINT PRIMARY KEY CHECK (id = 1),
    restart_policy            TEXT NOT NULL DEFAULT 'always',
    max_restarts              BIGINT NOT NULL DEFAULT 10,
    restart_delay_ms          BIGINT NOT NULL DEFAULT 3000,
    health_check_interval_ms  BIGINT NOT NULL DEFAULT 5000,
    health_check_timeout_ms   BIGINT NOT NULL DEFAULT 30000,
    health_check_retries      BIGINT NOT NULL DEFAULT 3
);

CREATE TABLE app_proxy (
    id                              BIGINT PRIMARY KEY CHECK (id = 1),
    host                            TEXT NOT NULL DEFAULT '0.0.0.0',
    port                            BIGINT NOT NULL DEFAULT 11434,
    auto_unload                     BOOLEAN NOT NULL DEFAULT FALSE,
    idle_timeout_secs               BIGINT NOT NULL DEFAULT 300,
    startup_timeout_secs            BIGINT NOT NULL DEFAULT 120,
    circuit_breaker_threshold       BIGINT NOT NULL DEFAULT 3,
    circuit_breaker_cooldown_seconds BIGINT NOT NULL DEFAULT 60,
    metrics_retention_secs          BIGINT NOT NULL DEFAULT 86400,
    pull_queue_poll_interval_secs   BIGINT NOT NULL DEFAULT 2,
    max_loaded_models               BIGINT NOT NULL DEFAULT 1,
    authenticator_url               TEXT,
    authenticator_skip_paths        TEXT NOT NULL DEFAULT '["/health","/metrics"]',
    oauth2_enabled                  BOOLEAN NOT NULL DEFAULT FALSE,
    oauth2_client_id                TEXT NOT NULL DEFAULT '',
    oauth2_client_secret            TEXT NOT NULL DEFAULT '',
    oauth2_authorize_url            TEXT NOT NULL DEFAULT '',
    oauth2_token_url                TEXT NOT NULL DEFAULT '',
    oauth2_userinfo_url             TEXT,
    oauth2_logout_url               TEXT,
    oauth2_redirect_uri             TEXT NOT NULL DEFAULT '',
    oauth2_scopes                   TEXT NOT NULL DEFAULT '["openid","profile","email"]',
    oauth2_session_ttl_secs         BIGINT NOT NULL DEFAULT 86400,
    api_keys_enabled                BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE benchmarks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        BIGINT NOT NULL,
    model_id          TEXT NOT NULL,
    display_name      TEXT,
    quant             TEXT,
    backend           TEXT NOT NULL,
    engine            TEXT NOT NULL DEFAULT 'llama_bench',
    pp_sizes          TEXT NOT NULL,
    tg_sizes          TEXT NOT NULL,
    threads           TEXT,
    ngl_range         TEXT,
    runs              BIGINT NOT NULL DEFAULT 3,
    warmup            BIGINT NOT NULL DEFAULT 1,
    results           TEXT NOT NULL,
    load_time_ms      DOUBLE PRECISION,
    vram_used_mib     BIGINT,
    vram_total_mib    BIGINT,
    duration_seconds  DOUBLE PRECISION,
    status            TEXT NOT NULL DEFAULT 'success',
    benchmark_type    TEXT,
    suite_id          TEXT
);

CREATE TABLE provider_configs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_id       TEXT,
    name             TEXT NOT NULL,
    gpu_variant      TEXT NOT NULL DEFAULT 'cpu',
    default_args     TEXT,
    health_check_url TEXT,
    default_env      TEXT,
    UNIQUE (logical_id, gpu_variant)
);

CREATE TABLE provider_installations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    backend_type TEXT NOT NULL,
    version      TEXT NOT NULL,
    path         TEXT NOT NULL,
    installed_at BIGINT NOT NULL,
    gpu_variant  TEXT NOT NULL DEFAULT 'cpu',
    source       TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT FALSE,
    docker_config TEXT,
    logical_id   TEXT,
    UNIQUE (name, gpu_variant, version)
);

CREATE TABLE provider_registry (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    provider_type TEXT NOT NULL CHECK (provider_type IN ('local', 'remote')),
    engine        TEXT NOT NULL,
    tamad_id      TEXT,
    base_url      TEXT,
    api_key       TEXT,
    created_at    BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())::BIGINT)
);

CREATE TABLE pull_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id        TEXT NOT NULL,
    filename       TEXT NOT NULL,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at   TIMESTAMPTZ,
    size_bytes     BIGINT,
    duration_ms    BIGINT,
    success        BOOLEAN NOT NULL DEFAULT FALSE,
    error_message  TEXT
);

CREATE TABLE pull_queue (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           TEXT NOT NULL UNIQUE,
    repo_id          TEXT NOT NULL,
    filename         TEXT NOT NULL,
    display_name     TEXT,
    status           TEXT NOT NULL DEFAULT 'queued',
    bytes_pulled     BIGINT NOT NULL DEFAULT 0,
    total_bytes      BIGINT,
    error_message    TEXT,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    queued_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    kind             TEXT NOT NULL DEFAULT 'model',
    quant            TEXT,
    context_length   BIGINT
);

CREATE TABLE sampling_templates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT UNIQUE NOT NULL,
    temperature       DOUBLE PRECISION,
    top_k             BIGINT,
    top_p             DOUBLE PRECISION,
    min_p             DOUBLE PRECISION,
    presence_penalty  DOUBLE PRECISION,
    frequency_penalty DOUBLE PRECISION,
    repeat_penalty    DOUBLE PRECISION
);

CREATE TABLE system_metrics_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts_unix_ms        BIGINT NOT NULL,
    cpu_usage_pct     DOUBLE PRECISION NOT NULL,
    ram_used_mib      BIGINT NOT NULL,
    ram_total_mib     BIGINT NOT NULL,
    gpu_utilization_pct BIGINT,
    vram_used_mib     BIGINT,
    vram_total_mib    BIGINT,
    models_loaded     BIGINT NOT NULL,
    tps               DOUBLE PRECISION,
    prompt_tps        DOUBLE PRECISION,
    cache_hit_pct     DOUBLE PRECISION,
    spec_accept_pct   DOUBLE PRECISION,
    net_rx_bytes      BIGINT DEFAULT 0,
    net_tx_bytes      BIGINT DEFAULT 0
);

CREATE TABLE tamad_registry (
    id        TEXT PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE,
    url       TEXT NOT NULL,
    protocol  TEXT NOT NULL CHECK (protocol IN ('grpc', 'http')),
    token     TEXT,
    status    TEXT NOT NULL DEFAULT 'unknown' CHECK (status IN ('online', 'offline', 'unknown'))
);

CREATE TABLE tts_configs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine         TEXT NOT NULL UNIQUE,
    default_voice  TEXT,
    speed          DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    format         TEXT NOT NULL DEFAULT 'mp3',
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE update_checks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type        TEXT NOT NULL,
    item_id          TEXT NOT NULL,
    current_version  TEXT,
    latest_version   TEXT,
    update_available BOOLEAN NOT NULL DEFAULT FALSE,
    status           TEXT NOT NULL DEFAULT 'unknown',
    error_message    TEXT,
    details_json     TEXT,
    checked_at       BIGINT NOT NULL,
    UNIQUE (item_type, item_id)
);

-- Indexes that still exist at v49.
CREATE INDEX idx_api_keys_active_created ON api_keys (revoked_at, created_at DESC);
CREATE INDEX idx_benchmarks_created_at ON benchmarks(created_at DESC);
CREATE INDEX idx_benchmarks_model_id ON benchmarks(model_id);
CREATE INDEX idx_dq_status ON pull_queue(status);
CREATE INDEX idx_model_aliases_enabled ON model_aliases(enabled);
CREATE INDEX idx_model_aliases_model_id ON model_aliases(model_id);
CREATE UNIQUE INDEX idx_model_configs_repo_id_lower ON model_configs (lower(repo_id));
CREATE UNIQUE INDEX idx_model_files_model_id_filename ON model_files(model_id, filename);
CREATE UNIQUE INDEX idx_model_pulls_model_id ON model_pulls(model_id);
CREATE INDEX idx_provider_configs_logical_variant ON provider_configs(logical_id, gpu_variant);
CREATE INDEX idx_provider_configs_name_variant ON provider_configs(name, gpu_variant);
CREATE INDEX idx_provider_installations_name ON provider_installations(name);
CREATE INDEX idx_provider_installations_name_variant ON provider_installations(name, gpu_variant);
CREATE INDEX idx_pull_log_repo ON pull_log(repo_id);
CREATE INDEX idx_system_metrics_ts ON system_metrics_history(ts_unix_ms);
CREATE INDEX idx_update_checks_type ON update_checks(item_type);
