[package]
name = "tamad"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tama-core = { path = "../tama-core" }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio-stream = { version = "0.1", features = ["sync"] }
futures-util = { workspace = true }
async-stream = { workspace = true }
reqwest = { workspace = true }
sysinfo = { workspace = true }
rand = { workspace = true }
hostname = "0.4"
url = { workspace = true }
uuid = { version = "1", features = ["v4"] }
libc = "0.2.183"
include_dir = "0.7"
zip = "6.0"
flate2 = "1.0"
tar = "0.4"
glob = "0.3"
tokio-util = "0.7"
indicatif.workspace = true
tempfile = { workspace = true }

[dev-dependencies]
tama-mock = { path = "../tama-mock" }
wiremock = "0.6"
sha2 = "0.10"
