-- v49 final SQLite schema — generated by applying all 49 migrations in order.
-- Committed fixture (NOT regenerated at test time). One statement per object.
CREATE TABLE active_models (
            server_name TEXT PRIMARY KEY,   -- config key, e.g. "my-coding-model"
            model_name TEXT NOT NULL,       -- model identifier used for loading
            backend TEXT NOT NULL,          -- backend key, e.g. "llama-server"
            pid INTEGER NOT NULL,           -- backend process PID (i64 in Rust)
            port INTEGER NOT NULL,          -- backend port (i64 in Rust)
            backend_url TEXT NOT NULL,      -- full URL, e.g. "http://127.0.0.1:54321"
            loaded_at TEXT NOT NULL,        -- ISO 8601 timestamp
            last_accessed TEXT NOT NULL     -- ISO 8601 timestamp, updated periodically
        , backend_id TEXT);
CREATE TABLE api_keys (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL DEFAULT '',
            key_prefix TEXT NOT NULL,
            key_hash TEXT NOT NULL UNIQUE,
            scopes TEXT NOT NULL,
            created_by TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
            last_used_at TEXT,
            revoked_at TEXT,
            expires_at TEXT
        );
CREATE TABLE app_compaction (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            enabled INTEGER NOT NULL DEFAULT 0,
            server_path TEXT,
            device TEXT NOT NULL DEFAULT 'cpu',
            port INTEGER,
            request_timeout_ms INTEGER NOT NULL DEFAULT 30000
        );
CREATE TABLE app_general (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            log_level TEXT NOT NULL DEFAULT 'info',
            models_dir TEXT,
            logs_dir TEXT,
            hf_token TEXT,
            update_check_interval INTEGER NOT NULL DEFAULT 12,
            log_directives TEXT,
            log_retention_days INTEGER NOT NULL DEFAULT 7,
            log_retention_rows BIGINT NOT NULL DEFAULT 50000,
            log_retention_max_mb BIGINT NOT NULL DEFAULT 256
        );
CREATE TABLE app_langfuse (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        enabled INTEGER NOT NULL DEFAULT 0,
        public_key TEXT NOT NULL DEFAULT '',
        secret_key TEXT NOT NULL DEFAULT '',
        host TEXT NOT NULL DEFAULT 'https://cloud.langfuse.com',
        environment TEXT NOT NULL DEFAULT 'default',
        capture_input INTEGER NOT NULL DEFAULT 1,
        capture_output INTEGER NOT NULL DEFAULT 1,
        capture_streaming INTEGER NOT NULL DEFAULT 1,
        telemetry_max_bytes INTEGER NOT NULL DEFAULT 1048576,
        electricity_price_per_kwh REAL NOT NULL DEFAULT 0.0
    );
CREATE TABLE "app_lifecycle" (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            restart_policy TEXT NOT NULL DEFAULT 'always',
            max_restarts INTEGER NOT NULL DEFAULT 10,
            restart_delay_ms INTEGER NOT NULL DEFAULT 3000,
            health_check_interval_ms INTEGER NOT NULL DEFAULT 5000,
            health_check_timeout_ms INTEGER NOT NULL DEFAULT 30000,
            health_check_retries INTEGER NOT NULL DEFAULT 3
        );
CREATE TABLE app_proxy (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            host TEXT NOT NULL DEFAULT '0.0.0.0',
            port INTEGER NOT NULL DEFAULT 11434,
            auto_unload INTEGER NOT NULL DEFAULT 0,
            idle_timeout_secs INTEGER NOT NULL DEFAULT 300,
            startup_timeout_secs INTEGER NOT NULL DEFAULT 120,
            circuit_breaker_threshold INTEGER NOT NULL DEFAULT 3,
            circuit_breaker_cooldown_seconds INTEGER NOT NULL DEFAULT 60,
            metrics_retention_secs INTEGER NOT NULL DEFAULT 86400,
            pull_queue_poll_interval_secs INTEGER NOT NULL DEFAULT 2,
            max_loaded_models INTEGER NOT NULL DEFAULT 1,
            authenticator_url TEXT,
            authenticator_skip_paths TEXT NOT NULL DEFAULT '["/health","/metrics"]'
        , oauth2_enabled INTEGER NOT NULL DEFAULT 0, oauth2_client_id TEXT NOT NULL DEFAULT '', oauth2_client_secret TEXT NOT NULL DEFAULT '', oauth2_authorize_url TEXT NOT NULL DEFAULT '', oauth2_token_url TEXT NOT NULL DEFAULT '', oauth2_userinfo_url TEXT, oauth2_logout_url TEXT, oauth2_redirect_uri TEXT NOT NULL DEFAULT '', oauth2_scopes TEXT NOT NULL DEFAULT '["openid","profile","email"]', oauth2_session_ttl_secs INTEGER NOT NULL DEFAULT 86400, api_keys_enabled INTEGER NOT NULL DEFAULT 0, pull_backend TEXT);
CREATE TABLE benchmarks (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at          INTEGER NOT NULL,           -- Unix timestamp (seconds)
            model_id            TEXT NOT NULL,              -- Model config key (e.g. "qwen7b")
            display_name        TEXT,                       -- Model display name
            quant               TEXT,                       -- Quantization label (e.g. "Q4_K_M")
            backend             TEXT NOT NULL,              -- Backend type (e.g. "llama_cpp")
            engine              TEXT NOT NULL DEFAULT 'llama_bench',
            pp_sizes            TEXT NOT NULL,              -- JSON array, e.g. "[512,1024]"
            tg_sizes            TEXT NOT NULL,              -- JSON array, e.g. "[128,256]"
            threads             TEXT,                       -- JSON array or null
            ngl_range           TEXT,                       -- GPU layers range or null
            runs                INTEGER NOT NULL DEFAULT 3,
            warmup              INTEGER NOT NULL DEFAULT 1,
            results             TEXT NOT NULL,              -- JSON array of BenchSummary objects
            load_time_ms        REAL,                       -- Model load time in ms
            vram_used_mib       INTEGER,                    -- VRAM used at benchmark time
            vram_total_mib      INTEGER,                    -- Total VRAM
            duration_seconds    REAL,                       -- How long the benchmark took
            status              TEXT NOT NULL DEFAULT 'success'
        , benchmark_type TEXT, suite_id TEXT);
CREATE TABLE model_aliases (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE COLLATE NOCASE,
            model_id INTEGER NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
            description TEXT,
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        );
CREATE TABLE "model_configs" (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            repo_id       TEXT NOT NULL UNIQUE COLLATE NOCASE,
            display_name  TEXT,
            backend       TEXT NOT NULL DEFAULT 'llama_cpp',
            gpu_variant   TEXT,
            enabled       INTEGER NOT NULL DEFAULT 1,
            selected_quant  TEXT,
            selected_mmproj TEXT,
            context_length  INTEGER,
            num_parallel    INTEGER DEFAULT 0 CHECK(num_parallel >= 0),
            kv_unified      INTEGER NOT NULL DEFAULT 0,
            gpu_layers      INTEGER,
            cache_type_k    TEXT,
            cache_type_v    TEXT,
            port            INTEGER,
            args            TEXT,
            sampling        TEXT,
            modalities      TEXT,
            profile         TEXT,
            api_name        TEXT,
            health_check    TEXT,
            hf_format       TEXT,
            hf_base_model   TEXT,
            hf_pipeline_tag TEXT,
            hf_total_params TEXT,
            hf_active_params TEXT,
            hf_architecture_type TEXT,
            hf_context_length INTEGER,
            hf_num_layers   INTEGER,
            hf_last_modified TEXT,
            spec_decoding   TEXT,
            created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        , selected_mtp_model TEXT COLLATE NOCASE, gpu_device TEXT, n_batch INTEGER, n_ubatch INTEGER, vllm_config TEXT DEFAULT NULL, backend_id TEXT, provider_name TEXT, reasoning_levels TEXT DEFAULT NULL);
CREATE TABLE model_files (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            model_id   INTEGER NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
            repo_id    TEXT NOT NULL,                              -- cached for convenience
            filename   TEXT NOT NULL,                              -- e.g. "gemma-4-26B-Q4_K_M.gguf"
            quant      TEXT,                                       -- e.g. "Q4_K_M"
            lfs_oid    TEXT,                                       -- LFS SHA256 content hash
            size_bytes INTEGER,                                    -- file size in bytes
            pulled_at     TEXT NOT NULL,                       -- ISO 8601 timestamp
            last_verified_at   TEXT,                                 -- ISO 8601, cleared on hash change
            verified_ok       INTEGER,                               -- 1=ok, 0=mismatch, NULL=never verified
            verify_error      TEXT,                                  -- short error message
            kind TEXT NOT NULL DEFAULT 'model'                      -- 'model' or 'mmproj'
        );
CREATE TABLE model_pulls (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            model_id   INTEGER NOT NULL REFERENCES model_configs(id) ON DELETE CASCADE,
            repo_id    TEXT NOT NULL,                              -- cached for convenience
            commit_sha TEXT NOT NULL,                              -- HF repo HEAD commit hash
            pulled_at  TEXT NOT NULL                               -- ISO 8601 timestamp
        );
CREATE TABLE "provider_configs" (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            logical_id TEXT,
            name TEXT NOT NULL,
            gpu_variant TEXT NOT NULL DEFAULT 'cpu',
            default_args TEXT,
            health_check_url TEXT,
            default_env TEXT,
            UNIQUE(logical_id, gpu_variant)
        );
CREATE TABLE "provider_installations" (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            backend_type TEXT NOT NULL,
            version TEXT NOT NULL,
            path TEXT NOT NULL,
            installed_at INTEGER NOT NULL,
            gpu_variant TEXT NOT NULL DEFAULT 'cpu',
            source TEXT,
            is_active INTEGER NOT NULL DEFAULT 0, docker_config TEXT DEFAULT NULL, logical_id TEXT,
            UNIQUE(name, gpu_variant, version)
        );
CREATE TABLE provider_registry (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE,
        provider_type TEXT NOT NULL CHECK(provider_type IN ('local', 'remote')),
        engine TEXT NOT NULL,
        tamad_id TEXT,
        base_url TEXT,
        api_key TEXT,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
    );
CREATE TABLE pull_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            repo_id TEXT NOT NULL,
            filename TEXT NOT NULL,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            size_bytes INTEGER,              -- i64 in Rust
            duration_ms INTEGER,             -- i64 in Rust
            success INTEGER NOT NULL DEFAULT 0,
            error_message TEXT
        );
CREATE TABLE "pull_queue" (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            job_id        TEXT NOT NULL UNIQUE,
            repo_id       TEXT NOT NULL,
            filename      TEXT NOT NULL,
            display_name  TEXT,
            status        TEXT NOT NULL DEFAULT 'queued',
            bytes_pulled INTEGER NOT NULL DEFAULT 0,
            total_bytes     INTEGER,
            error_message TEXT,
            started_at     TEXT,
            completed_at   TEXT,
            queued_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            kind           TEXT NOT NULL DEFAULT 'model'
        , quant TEXT, context_length INTEGER);
CREATE TABLE sampling_templates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            temperature REAL,
            top_k INTEGER,
            top_p REAL,
            min_p REAL,
            presence_penalty REAL,
            frequency_penalty REAL,
            repeat_penalty REAL
        );
CREATE TABLE system_metrics_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ts_unix_ms          INTEGER NOT NULL,
            cpu_usage_pct       REAL    NOT NULL,
            ram_used_mib        INTEGER NOT NULL,
            ram_total_mib       INTEGER NOT NULL,
            gpu_utilization_pct INTEGER,
            vram_used_mib       INTEGER,
            vram_total_mib      INTEGER,
            models_loaded       INTEGER NOT NULL
        , tps REAL, prompt_tps REAL, cache_hit_pct REAL, spec_accept_pct REAL, net_rx_bytes BIGINT DEFAULT 0, net_tx_bytes BIGINT DEFAULT 0);
CREATE TABLE tamad_registry (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        url TEXT NOT NULL,
        protocol TEXT NOT NULL CHECK(protocol IN ('grpc', 'http')),
        token TEXT,
        status TEXT NOT NULL DEFAULT 'unknown' CHECK(status IN ('online', 'offline', 'unknown'))
    );
CREATE TABLE tts_configs (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            engine       TEXT NOT NULL UNIQUE COLLATE NOCASE,  -- TTS engine name (e.g., 'kokoro')
            default_voice TEXT,                                -- e.g., 'af_sky'
            speed        REAL   NOT NULL DEFAULT 1.0,          -- 0.5 to 2.0
            format       TEXT   NOT NULL DEFAULT 'mp3',        -- mp3, wav, ogg
            enabled      INTEGER NOT NULL DEFAULT 1,
            created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        );
CREATE TABLE update_checks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            item_type TEXT NOT NULL,           -- 'backend' or 'model'
            item_id TEXT NOT NULL,             -- backend name or model config key
            current_version TEXT,              -- installed version/commit SHA
            latest_version TEXT,               -- remote version/commit SHA
            update_available INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'unknown',
            error_message TEXT,
            details_json TEXT,                 -- JSON blob (per-file changes for models)
            checked_at INTEGER NOT NULL,        -- unix timestamp
            UNIQUE(item_type, item_id)
        );
CREATE INDEX idx_api_keys_active_created ON api_keys (revoked_at, created_at DESC);
CREATE INDEX idx_benchmarks_created_at ON benchmarks(created_at DESC);
CREATE INDEX idx_benchmarks_model_id ON benchmarks(model_id);
CREATE INDEX idx_dq_status ON "pull_queue"(status);
CREATE INDEX idx_model_aliases_enabled ON model_aliases(enabled);
CREATE INDEX idx_model_aliases_model_id ON model_aliases(model_id);
CREATE UNIQUE INDEX idx_model_files_model_id_filename ON model_files(model_id, filename);
CREATE UNIQUE INDEX idx_model_pulls_model_id
            ON model_pulls(model_id);
CREATE INDEX idx_provider_configs_logical_variant ON provider_configs(logical_id, gpu_variant);
CREATE INDEX idx_provider_configs_name_variant ON provider_configs(name, gpu_variant);
CREATE INDEX idx_provider_installations_name ON provider_installations(name);
CREATE INDEX idx_provider_installations_name_variant ON provider_installations(name, gpu_variant);
CREATE INDEX idx_pull_log_repo ON pull_log(repo_id);
CREATE INDEX idx_system_metrics_ts
            ON system_metrics_history(ts_unix_ms);
CREATE INDEX idx_update_checks_type ON update_checks(item_type);
