//! One-time v2→v3 cutover: `tama migrate` (plan-190 Task 10).
//!
//! Copies the v2 SQLite `tama.db` (schema v49) into Postgres and writes the
//! v3 bootstrap `config.toml`. The SQLite file is opened read-only
//! (`OpenFlags::SQLITE_OPEN_READ_ONLY`) and is never modified.
//!
//! Behavior:
//! - refuses if the SQLite schema is older than v49 (upgrade the v2 binary
//!   first) or if the Postgres target already has data / a bootstrap
//!   `config.toml` exists — unless `--force`.
//! - `--dry-run` reports per-table counts and writes nothing.
//! - the real run copies every table in ONE transaction with explicit ids
//!   (`ON CONFLICT (id) DO NOTHING` makes `--force` re-runs idempotent),
//!   advances identity sequences past the max migrated id, writes
//!   `migrate-report-<ts>.json` next to the SQLite file, and only then
//!   writes the bootstrap `config.toml`.
//! - per-row decode failures (NULL where NOT NULL, bad boolean, bad
//!   timestamp) are recorded in the report, not fatal; child rows whose
//!   parent was skipped land in the report via their FK error.

use anyhow::{bail, Context, Result};
use percent_encoding::{percent_decode, utf8_percent_encode, AsciiSet, CONTROLS};
use rusqlite::{types::Value, Connection, OpenFlags};
use serde::Serialize;
use sqlx::postgres::{PgConnection, PgPoolOptions};
use sqlx::{PgPool, QueryBuilder, Transaction};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Duration;
use tama_core::config::Config;
use time::format_description::well_known::Rfc3339;
use time::{OffsetDateTime, PrimitiveDateTime};

/// Minimum SQLite schema version this tool can read (v49 = final v2 schema).
const MIN_USER_VERSION: i32 = 49;

/// Rows per batched insert.
const BATCH_SIZE: usize = 500;

/// The percent-encode set for userinfo in a URL (same set the bootstrap
/// loader uses when building DSNs).
const USERINFO_ENCODE_SET: &AsciiSet = &CONTROLS
    .add(b' ')
    .add(b'"')
    .add(b'#')
    .add(b'%')
    .add(b'<')
    .add(b'>')
    .add(b'\\')
    .add(b'^')
    .add(b'`')
    .add(b'|')
    .add(b'}')
    .add(b':')
    .add(b'@')
    .add(b'/')
    .add(b'?')
    .add(b'[')
    .add(b']');

/// Tables in a conservative parents-first order.
///
/// Rationale: the v49 SQLite DDL declares only 3 real FKs —
/// `model_pulls.model_id`, `model_files.model_id` and `model_aliases.model_id`
/// (all → `model_configs(id) ON DELETE CASCADE`), and the squashed v1
/// Postgres migration introduces real FKs only where SQLite declared them.
/// Everything else is ordered by convention (config singletons first,
/// history tables last).
const TABLES: &[&str] = &[
    // Config singletons.
    "app_compaction",
    "app_general",
    "app_langfuse",
    "app_lifecycle",
    "app_proxy",
    // FK target before its children.
    "model_configs",
    "model_files",
    "model_pulls",
    "model_aliases",
    "provider_configs",
    "provider_registry",
    "api_keys",
    "pull_log",
    "pull_queue",
    "tamad_registry",
    "benchmarks",
    "sampling_templates",
    "tts_configs",
    "provider_installations",
    "update_checks",
    "system_metrics_history",
    "active_models",
];

/// Primary key column (used for `ORDER BY` and the `ON CONFLICT` target).
fn pk_column(table: &str) -> &'static str {
    if table == "active_models" {
        "server_name"
    } else {
        "id"
    }
}

/// Tables whose `id` is a Postgres `GENERATED BY DEFAULT AS IDENTITY`
/// column (everything except the TEXT-PK tables).
fn is_identity_table(table: &str) -> bool {
    !matches!(table, "active_models" | "tamad_registry")
}

/// Legacy source-table alias for a canonical [`TABLES`] entry.
///
/// `pull_log` was renamed from `download_log` in plan-150, but that rename
/// edited migration _0001 in place instead of adding a new migration, so real
/// v2 production DBs built by older binaries have `download_log` and no
/// `pull_log` (fresh DBs have `pull_log`). The two tables have identical
/// columns, so either name is a valid source; rows always land in the
/// canonical Postgres table.
fn table_alias(table: &str) -> &'static str {
    match table {
        "pull_log" => "download_log",
        _ => "",
    }
}

/// Resolve the actual SQLite source table for a canonical [`TABLES`] entry.
///
/// Prefers the canonical name, falls back to its legacy alias, and returns
/// `None` when neither exists (so the caller can soft-skip the table instead
/// of erroring on a `no such table`).
fn source_table_name(db: &Connection, canonical: &str, alias: &str) -> Result<Option<String>> {
    let exists = |name: &str| -> Result<bool> {
        let n: i64 = db.query_row(
            "SELECT count(*) FROM sqlite_master WHERE type = 'table' AND name = ?1",
            [name],
            |r| r.get(0),
        )?;
        Ok(n > 0)
    };
    if exists(canonical)? {
        return Ok(Some(canonical.to_string()));
    }
    if !alias.is_empty() && exists(alias)? {
        return Ok(Some(alias.to_string()));
    }
    Ok(None)
}

/// Options for [`run`].
#[derive(Debug, Clone)]
pub struct MigrateOpts {
    /// Path to the v2 SQLite database.
    pub sqlite_path: PathBuf,
    /// Postgres connection URL (`postgres://user:pass@host:port/db`).
    pub db_url: String,
    /// Env var holding the Postgres password (recommended over a `--db`
    /// password).
    pub password_env: Option<String>,
    /// Report per-table counts only; write nothing.
    pub dry_run: bool,
    /// Allow a populated target and an existing bootstrap config.toml
    /// (backed up to `config.toml.bak-<ts>` first).
    pub force: bool,
    /// Override the directory the bootstrap config.toml is written to
    /// (tests only; `None` → `Config::config_dir()`).
    pub config_dir_override: Option<PathBuf>,
}

impl MigrateOpts {
    /// Build options from parsed CLI args.
    pub fn from_cli(args: crate::cli::MigrateArgs) -> Self {
        Self {
            sqlite_path: args.sqlite,
            db_url: args.db,
            password_env: args.password_env,
            dry_run: args.dry_run,
            force: args.force,
            config_dir_override: None,
        }
    }
}

/// A row that could not be copied (decode failure or FK violation).
#[derive(Debug, Clone, Serialize)]
pub struct SkippedRow {
    pub table: String,
    pub id: String,
    pub error: String,
}

/// Outcome of a migration run; serialized to `migrate-report-<ts>.json`.
#[derive(Debug, Clone, Serialize)]
pub struct MigrationReport {
    pub dry_run: bool,
    /// Whether the migration transaction committed. `false` on the abort
    /// path, where `inserted` is zeroed (the attempted inserts rolled back).
    pub committed: bool,
    /// table → `[sqlite_rows, postgres_rows_before]`
    pub counts: BTreeMap<String, [u64; 2]>,
    /// table → rows inserted this run (0 in a dry run or when the run
    /// aborted — the transaction rolled back, so nothing was committed)
    pub inserted: BTreeMap<String, u64>,
    pub skipped: Vec<SkippedRow>,
    /// Where the JSON report was written (None in a dry run).
    pub report_path: Option<String>,
}

/// Parsed `--db` URL with user/password percent-decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DbTarget {
    pub host: String,
    pub port: u16,
    pub user: String,
    pub password: Option<String>,
    pub database: String,
    /// Extra query parameters preserved verbatim (e.g. `sslmode`,
    /// `options`).
    pub query: String,
}

impl DbTarget {
    /// Rebuild a sqlx DSN with the resolved password, percent-encoding
    /// user/password so `@`/`:`/`%` survive.
    pub fn dsn(&self, password: &str) -> String {
        let user = utf8_percent_encode(&self.user, USERINFO_ENCODE_SET);
        let pass = utf8_percent_encode(password, USERINFO_ENCODE_SET);
        let mut dsn = format!(
            "postgres://{user}:{pass}@{}:{}/{}",
            self.host, self.port, self.database
        );
        if !self.query.is_empty() {
            dsn.push('?');
            dsn.push_str(&self.query);
        }
        dsn
    }
}

/// Parse a `--db` URL, percent-decoding the user and password so values
/// containing `@`, `:` or `%` survive.
pub fn parse_db_url(url: &str) -> Result<DbTarget> {
    let u = url::Url::parse(url).with_context(|| format!("invalid --db URL: {url}"))?;
    if !matches!(u.scheme(), "postgres" | "postgresql") {
        bail!("--db URL must use the postgres:// or postgresql:// scheme");
    }
    let host = u
        .host_str()
        .context("--db URL is missing a host")?
        .to_string();
    let port = u.port().unwrap_or(5432);
    let user = percent_decode(u.username().as_bytes())
        .decode_utf8_lossy()
        .into_owned();
    let password = u.password().map(|p| {
        percent_decode(p.as_bytes())
            .decode_utf8_lossy()
            .into_owned()
    });
    let database = u.path().trim_start_matches('/').to_string();
    if database.is_empty() {
        bail!("--db URL is missing a database name");
    }
    let query = u.query().unwrap_or_default().to_string();
    Ok(DbTarget {
        host,
        port,
        user,
        password,
        database,
        query,
    })
}

/// Run the migration.
pub async fn run(opts: MigrateOpts) -> Result<MigrationReport> {
    let unix_ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // 1. Open the SQLite db READ-ONLY at the OS level — the tool never
    //    writes it, even on a read-only filesystem or mount.
    let sqlite = Connection::open_with_flags(&opts.sqlite_path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .with_context(|| format!("opening SQLite db {}", opts.sqlite_path.display()))?;

    // 2. Schema version gate.
    let user_version: i32 = sqlite
        .query_row("PRAGMA user_version", [], |r| r.get(0))
        .context("reading PRAGMA user_version")?;
    if user_version < MIN_USER_VERSION {
        bail!(
            "SQLite schema is v{user_version}, but v{MIN_USER_VERSION} is required — \
             upgrade the v2 binary first (it migrates tama.db in place), then re-run `tama migrate`"
        );
    }

    // 3. Target DSN (password from --password-env wins over the URL).
    let target = parse_db_url(&opts.db_url)?;
    let password = match &opts.password_env {
        Some(name) => {
            std::env::var(name).with_context(|| format!("--password-env {name} is not set"))?
        }
        None => target.password.clone().unwrap_or_default(),
    };

    // 4. Eager connect — fail fast with a clear error (no connect_lazy).
    let pool = PgPoolOptions::new()
        .max_connections(4)
        .acquire_timeout(Duration::from_secs(10))
        .connect(&target.dsn(&password))
        .await
        .with_context(|| {
            format!(
                "connecting to Postgres at {}:{}/{}",
                target.host, target.port, target.database
            )
        })?;

    let mut report = MigrationReport {
        dry_run: opts.dry_run,
        committed: true,
        counts: BTreeMap::new(),
        inserted: BTreeMap::new(),
        skipped: Vec::new(),
        report_path: None,
    };

    // 5. Dry run: per-table counts, write nothing (and do not create the
    //    schema — a dry run has no side effects).
    if opts.dry_run {
        for table in TABLES {
            let source = match source_table_name(&sqlite, table, table_alias(table))? {
                Some(s) => s,
                None => {
                    println!("skipping {table} (not present in source)");
                    let p = pg_count(&pool, table).await?;
                    report.counts.insert(table.to_string(), [0, p]);
                    continue;
                }
            };
            let s = sqlite_count(&sqlite, &source)?;
            let p = pg_count(&pool, table).await?;
            report.counts.insert(table.to_string(), [s, p]);
            println!("{table:<24} sqlite={s:<8} postgres={p}");
        }
        println!("\ndry run complete — nothing was written");
        pool.close().await;
        return Ok(report);
    }

    // 6. Refusal checks (unless --force).
    for table in ["model_configs", "api_keys", "app_general"] {
        let n = pg_count(&pool, table).await?;
        if n > 0 && !opts.force {
            bail!(
                "target Postgres already has data ({table} has {n} row(s)) — \
                 refusing to migrate over it. Re-run with --force to continue \
                 a partial migration (inserts are idempotent)"
            );
        }
    }
    let config_dir = match &opts.config_dir_override {
        Some(dir) => dir.clone(),
        None => Config::config_dir().context("determining the config directory")?,
    };
    let config_path = config_dir.join("config.toml");
    if config_path.exists() && !opts.force {
        bail!(
            "{} already exists — refusing to overwrite it. If this is the \
             bootstrap file from a previous partial run, re-run with --force \
             (it will be backed up to config.toml.bak-<ts> first)",
            config_path.display()
        );
    }

    // 7. Ensure the schema exists (idempotent; a no-op if tama already ran).
    tama_core::db::postgres::run_migrations(&pool)
        .await
        .context("applying the Postgres schema (idempotent)")?;

    // 8. Copy every table in ONE transaction.
    let mut tx = pool
        .begin()
        .await
        .context("beginning the migration transaction")?;
    let mut failed = false;
    for table in TABLES {
        let source = match source_table_name(&sqlite, table, table_alias(table))? {
            Some(s) => s,
            None => {
                println!("skipping {table} (not present in source)");
                let p = pg_count(&pool, table).await?;
                report.counts.insert(table.to_string(), [0, p]);
                report.inserted.insert(table.to_string(), 0);
                continue;
            }
        };
        let sqlite_n = sqlite_count(&sqlite, &source)?;
        let pg_n = pg_count(&pool, table).await?;
        report.counts.insert(table.to_string(), [sqlite_n, pg_n]);
        match copy_table(&mut tx, &sqlite, table, &source, &mut report.skipped).await {
            Ok(n) => {
                report.inserted.insert(table.to_string(), n);
                println!("{table:<24} {n} row(s)");
            }
            Err(e) => {
                eprintln!("{table:<24} FAILED: {e:#}");
                failed = true;
            }
        }
    }

    // 9. Write the report even on abort — it lists what failed. On the
    //    abort path the transaction rolled back, so mark the report
    //    uncommitted and zero the per-table counts (they were attempted,
    //    not committed).
    if failed {
        report.committed = false;
        report.inserted.clear();
    }
    let report_path = opts
        .sqlite_path
        .with_file_name(format!("migrate-report-{unix_ts}.json"));
    report.report_path = Some(report_path.to_string_lossy().into_owned());
    std::fs::write(&report_path, serde_json::to_string_pretty(&report)?)
        .with_context(|| format!("writing report {}", report_path.display()))?;

    if failed {
        for s in &report.skipped {
            eprintln!("  skipped {}.{}: {}", s.table, s.id, s.error);
        }
        tx.rollback()
            .await
            .context("rolling back after a table-level failure")?;
        pool.close().await;
        bail!(
            "migration aborted — target left untouched. \
             Details are in {}",
            report_path.display()
        );
    }

    // 10. Advance identity sequences past the max migrated id.
    let schema: String = sqlx::query_scalar("SELECT current_schema()")
        .fetch_one(&mut *tx)
        .await
        .context("reading the current schema")?;
    for table in TABLES {
        if !is_identity_table(table) {
            continue;
        }
        let sql = format!(
            "SELECT setval(pg_get_serial_sequence('{schema}.{table}', 'id'), \
             COALESCE(MAX(id), 0) + 1, false) FROM {table}"
        );
        sqlx::query(sqlx::AssertSqlSafe(sql))
            .execute(&mut *tx)
            .await
            .with_context(|| format!("advancing the sequence for {table}"))?;
    }

    tx.commit().await.context("committing the migration")?;

    // 11. Bootstrap config.toml — ONLY after the commit.
    write_bootstrap_config(
        &config_dir,
        &config_path,
        &target,
        &opts,
        &password,
        unix_ts,
    )?;

    // 12. Summary.
    let total: u64 = report.inserted.values().sum();
    println!(
        "\nMigrated {total} row(s) across {} table(s); {} row(s) skipped.",
        report.inserted.len(),
        report.skipped.len()
    );
    if !report.skipped.is_empty() {
        for s in &report.skipped {
            println!("  skipped {}.{}: {}", s.table, s.id, s.error);
        }
        println!("Full details: {}", report_path.display());
    }
    println!("Next step: start tama (`tama`).");
    pool.close().await;
    Ok(report)
}

/// `SELECT count(*)` on the SQLite side.
fn sqlite_count(sqlite: &Connection, table: &str) -> Result<u64> {
    let n: i64 = sqlite
        .query_row(&format!("SELECT count(*) FROM {table}"), [], |r| r.get(0))
        .with_context(|| format!("counting {table} in SQLite"))?;
    Ok(n as u64)
}

/// `SELECT count(*)` on the Postgres side; a missing table counts as 0.
async fn pg_count(pool: &PgPool, table: &str) -> Result<u64> {
    let sql = format!("SELECT count(*) FROM {table}");
    match sqlx::query_scalar::<_, i64>(sqlx::AssertSqlSafe(sql))
        .fetch_one(pool)
        .await
    {
        Ok(n) => Ok(n as u64),
        // 42P01 = undefined_table (fresh database, dry run).
        Err(sqlx::Error::Database(db)) if db.code().as_deref() == Some("42P01") => Ok(0),
        Err(e) => Err(e).with_context(|| format!("counting {table} in Postgres")),
    }
}

/// A SQLite value converted for its Postgres column type.
///
/// Each variant carries an `Option` so NULLs bind with a type matching the
/// target column (Postgres rejects a typed NULL of the wrong type).
#[derive(Debug, Clone)]
enum Val {
    I64(Option<i64>),
    F64(Option<f64>),
    Bool(Option<bool>),
    Text(Option<String>),
    Tz(Option<OffsetDateTime>),
    Naive(Option<PrimitiveDateTime>),
}

fn val_to_string(v: &Val) -> String {
    match v {
        Val::I64(Some(n)) => n.to_string(),
        Val::F64(Some(f)) => f.to_string(),
        Val::Bool(Some(b)) => b.to_string(),
        Val::Text(Some(s)) => s.clone(),
        Val::Tz(Some(t)) => t.to_string(),
        Val::Naive(Some(n)) => n.to_string(),
        _ => "NULL".to_string(),
    }
}

/// A NULL typed for the target column.
fn typed_null(data_type: &str) -> Val {
    match data_type {
        "bigint" => Val::I64(None),
        "double precision" => Val::F64(None),
        "boolean" => Val::Bool(None),
        "timestamp with time zone" => Val::Tz(None),
        "timestamp without time zone" => Val::Naive(None),
        _ => Val::Text(None),
    }
}

/// Convert a SQLite value for a Postgres column of `data_type`.
///
/// Failures here are per-row decode errors (reported, not fatal).
fn convert_value(v: Value, data_type: &str, nullable: bool) -> Result<Val> {
    match (v, data_type) {
        (Value::Null, _) => {
            if !nullable {
                bail!("NULL in NOT NULL column");
            }
            Ok(typed_null(data_type))
        }
        (Value::Integer(n), "boolean") => match n {
            0 => Ok(Val::Bool(Some(false))),
            1 => Ok(Val::Bool(Some(true))),
            _ => bail!("boolean column: expected 0/1, got {n}"),
        },
        (Value::Text(s), "boolean") => match s.trim().to_ascii_lowercase().as_str() {
            "true" | "t" | "yes" | "on" => Ok(Val::Bool(Some(true))),
            "false" | "f" | "no" | "off" => Ok(Val::Bool(Some(false))),
            _ => bail!("cannot parse {s:?} as boolean"),
        },
        (Value::Integer(n), "bigint") => Ok(Val::I64(Some(n))),
        (Value::Integer(n), "double precision") => Ok(Val::F64(Some(n as f64))),
        (Value::Real(f), "double precision") => Ok(Val::F64(Some(f))),
        (Value::Text(s), "text") => Ok(Val::Text(Some(s))),
        (Value::Text(s), "timestamp with time zone") => {
            let dt = OffsetDateTime::parse(&s, &Rfc3339)
                .with_context(|| format!("invalid timestamp {s:?}"))?;
            Ok(Val::Tz(Some(dt)))
        }
        (Value::Text(s), "timestamp without time zone") => {
            let dt = OffsetDateTime::parse(&s, &Rfc3339)
                .with_context(|| format!("invalid timestamp {s:?}"))?;
            Ok(Val::Naive(Some(PrimitiveDateTime::new(
                dt.date(),
                dt.time(),
            ))))
        }
        (Value::Text(s), other) => bail!("text value {s:?} for column of type {other}"),
        (Value::Integer(n), other) => bail!("integer value {n} for column of type {other}"),
        (Value::Real(f), other) => bail!("real value {f} for column of type {other}"),
        (Value::Blob(_), _) => bail!("BLOB value"),
    }
}

/// Copy one table: `SELECT * ORDER BY <pk>` from SQLite, batched
/// parameterized inserts with explicit ids into Postgres.
async fn copy_table(
    tx: &mut Transaction<'_, sqlx::Postgres>,
    sqlite: &Connection,
    table: &str,
    source: &str,
    skipped: &mut Vec<SkippedRow>,
) -> Result<u64> {
    let pk = pk_column(table);

    // Target column metadata: name → (data_type, nullable).
    let cols: Vec<(String, String, String)> = sqlx::query_as(
        "SELECT column_name, data_type, is_nullable \
         FROM information_schema.columns \
         WHERE table_schema = current_schema() AND table_name = $1 \
         ORDER BY ordinal_position",
    )
    .bind(table)
    .fetch_all(&mut **tx)
    .await
    .with_context(|| format!("reading column metadata for {table}"))?;
    if cols.is_empty() {
        bail!("table {table} does not exist in the target schema");
    }
    let meta: BTreeMap<&str, (&str, bool)> = cols
        .iter()
        .map(|(name, dt, nullable)| (name.as_str(), (dt.as_str(), nullable == "YES")))
        .collect();

    let sql = format!("SELECT * FROM {source} ORDER BY {pk}");
    let mut stmt = sqlite
        .prepare(&sql)
        .with_context(|| format!("preparing {sql}"))?;
    let sqlite_cols: Vec<String> = stmt.column_names().iter().map(|s| s.to_string()).collect();
    for col in &sqlite_cols {
        if !meta.contains_key(col.as_str()) {
            bail!(
                "column {table}.{col} exists in the SQLite db but not in the \
                 Postgres schema — schema drift; refusing to guess"
            );
        }
    }
    let pk_index = sqlite_cols
        .iter()
        .position(|c| c == pk)
        .with_context(|| format!("primary key column {pk} missing in {table}"))?;

    let mut rows = stmt
        .query([])
        .with_context(|| format!("querying {table} from SQLite"))?;
    let mut inserted = 0u64;
    let mut batch: Vec<Vec<Val>> = Vec::with_capacity(BATCH_SIZE);
    while let Some(row) = rows
        .next()
        .with_context(|| format!("reading a row from {table}"))?
    {
        let id_str = val_to_string(&match row.get_ref(pk_index)?.into() {
            Value::Integer(n) => Val::I64(Some(n)),
            Value::Text(s) => Val::Text(Some(s)),
            Value::Real(f) => Val::F64(Some(f)),
            Value::Null => Val::I64(None),
            Value::Blob(_) => Val::Text(Some("<blob>".to_string())),
        });
        let mut vals = Vec::with_capacity(sqlite_cols.len());
        let mut row_err: Option<String> = None;
        for (i, col) in sqlite_cols.iter().enumerate() {
            let v: Value = row.get_ref(i)?.into();
            let (dt, nullable) = meta[col.as_str()];
            match convert_value(v, dt, nullable) {
                Ok(cv) => vals.push(cv),
                Err(e) => {
                    row_err = Some(format!("{e:#}"));
                    break;
                }
            }
        }
        if let Some(e) = row_err {
            skipped.push(SkippedRow {
                table: table.to_string(),
                id: id_str,
                error: e,
            });
            continue;
        }
        batch.push(vals);
        if batch.len() == BATCH_SIZE {
            inserted += flush_batch(tx, table, &sqlite_cols, &batch, skipped).await?;
            batch.clear();
        }
    }
    if !batch.is_empty() {
        inserted += flush_batch(tx, table, &sqlite_cols, &batch, skipped).await?;
    }
    Ok(inserted)
}

/// Batched insert. A failed batch (e.g. one FK violation among valid rows)
/// is rolled back to a savepoint (via a nested transaction) and retried
/// row-by-row so only the offending rows are reported; the surrounding
/// transaction stays usable.
async fn flush_batch(
    tx: &mut Transaction<'_, sqlx::Postgres>,
    table: &str,
    cols: &[String],
    batch: &[Vec<Val>],
    skipped: &mut Vec<SkippedRow>,
) -> Result<u64> {
    // A nested transaction is a SAVEPOINT in Postgres.
    let mut nested: Transaction<'_, sqlx::Postgres> = Transaction::begin(&mut **tx, None)
        .await
        .with_context(|| format!("creating a savepoint for {table}"))?;
    let nested_conn: &mut PgConnection = &mut nested;
    match build_insert(nested_conn, table, cols, batch).await {
        Ok(n) => {
            nested
                .commit()
                .await
                .with_context(|| format!("releasing the savepoint for {table}"))?;
            Ok(n)
        }
        Err(batch_err) => {
            eprintln!("  batch insert into {table} failed: {batch_err:#}");
            nested
                .rollback()
                .await
                .with_context(|| format!("rolling back the failed {table} batch"))?;
            let pk = pk_column(table);
            let pk_index = cols
                .iter()
                .position(|c| c == pk)
                .with_context(|| format!("primary key column {pk} missing in {table}"))?;
            let mut ok_rows = 0u64;
            for vals in batch {
                let id = val_to_string(&vals[pk_index]);
                let mut row_tx: Transaction<'_, sqlx::Postgres> =
                    Transaction::begin(&mut **tx, None)
                        .await
                        .with_context(|| format!("creating a savepoint for {table}"))?;
                let row_conn: &mut PgConnection = &mut row_tx;
                match build_insert(row_conn, table, cols, std::slice::from_ref(vals)).await {
                    Ok(_) => {
                        row_tx
                            .commit()
                            .await
                            .with_context(|| format!("releasing the savepoint for {table}"))?;
                        ok_rows += 1;
                    }
                    Err(e) => {
                        row_tx
                            .rollback()
                            .await
                            .with_context(|| format!("rolling back the failed {table} row"))?;
                        skipped.push(SkippedRow {
                            table: table.to_string(),
                            id,
                            error: format!("{e:#}"),
                        });
                    }
                }
            }
            Ok(ok_rows)
        }
    }
}

/// Push a quoted SQL identifier (names come from trusted sources: the
/// `TABLES` constant or the target's `information_schema`).
fn push_ident(q: &mut QueryBuilder<sqlx::Postgres>, name: &str) {
    q.push(format!("\"{}\"", name.replace('"', "\"\"")));
}

/// Build and execute `INSERT INTO <table> (<cols>) VALUES (...) ON
/// CONFLICT (<pk>) DO NOTHING` for one or more rows.
async fn build_insert(
    tx: &mut PgConnection,
    table: &str,
    cols: &[String],
    rows: &[Vec<Val>],
) -> Result<u64> {
    let pk = pk_column(table);
    let mut q = QueryBuilder::<sqlx::Postgres>::new(String::new());
    q.push("INSERT INTO ");
    push_ident(&mut q, table);
    q.push(" (");
    for (i, col) in cols.iter().enumerate() {
        if i > 0 {
            q.push(", ");
        }
        push_ident(&mut q, col);
    }
    q.push(") ");
    // push_values emits the "VALUES " keyword and wraps each tuple in
    // parens; the inner Separated handles the ", " separators between binds.
    q.push_values(rows, |mut v, vals| {
        for val in vals {
            match val {
                Val::I64(n) => v.push_bind(n),
                Val::F64(f) => v.push_bind(f),
                Val::Bool(b) => v.push_bind(b),
                Val::Text(s) => v.push_bind(s),
                Val::Tz(t) => v.push_bind(t),
                Val::Naive(n) => v.push_bind(n),
            };
        }
    });
    q.push(" ON CONFLICT (");
    push_ident(&mut q, pk);
    q.push(") DO NOTHING");
    let result = q
        .build()
        .execute(&mut *tx)
        .await
        .with_context(|| format!("inserting into {table}"))?;
    Ok(result.rows_affected())
}

/// Write the bootstrap `config.toml` (only called after the commit).
///
/// An existing file (only possible with `--force`) is backed up to
/// `config.toml.bak-<ts>` first and its contents are updated in place,
/// preserving comments.
fn write_bootstrap_config(
    config_dir: &Path,
    config_path: &Path,
    target: &DbTarget,
    opts: &MigrateOpts,
    password: &str,
    unix_ts: u64,
) -> Result<()> {
    // Double safety — the pre-checks already guard this.
    let existing = if config_path.exists() {
        if !opts.force {
            bail!(
                "{} appeared since the pre-checks — refusing to overwrite it",
                config_path.display()
            );
        }
        let content = std::fs::read_to_string(config_path)
            .with_context(|| format!("reading {}", config_path.display()))?;
        let backup = config_path.with_extension(format!("toml.bak-{unix_ts}"));
        std::fs::rename(config_path, &backup).with_context(|| {
            format!(
                "backing up {} to {}",
                config_path.display(),
                backup.display()
            )
        })?;
        println!("Backed up existing config to {}", backup.display());
        Some(content)
    } else {
        None
    };

    let mut doc = match existing {
        Some(content) => content
            .parse::<toml_edit::DocumentMut>()
            .with_context(|| "parsing the existing config.toml")?,
        None => toml_edit::DocumentMut::new(),
    };
    let db = doc
        .as_table_mut()
        .entry("database")
        .or_insert(toml_edit::Item::Table(toml_edit::Table::new()));
    if let toml_edit::Item::Table(t) = db {
        t["host"] = toml_edit::value(target.host.as_str());
        t["port"] = toml_edit::value(target.port as i64);
        t["name"] = toml_edit::value(target.database.as_str());
        t["user"] = toml_edit::value(target.user.as_str());
        t["password"] = match &opts.password_env {
            Some(name) => toml_edit::value(format!("${{{name}}}")),
            None => toml_edit::value(password),
        };
    }

    std::fs::create_dir_all(config_dir)
        .with_context(|| format!("creating {}", config_dir.display()))?;
    std::fs::write(config_path, doc.to_string())
        .with_context(|| format!("writing {}", config_path.display()))?;
    println!("Wrote bootstrap config {}", config_path.display());
    match &opts.password_env {
        Some(name) => println!(
            "Note: the password is read from env var {name} at startup — \
             make sure it is set in the service environment."
        ),
        None => println!(
            "Warning: the Postgres password is stored literally in config.toml — \
             prefer --password-env <NAME>"
        ),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_db_url_plain() {
        let t = parse_db_url("postgres://tama@127.0.0.1:5432/tama").expect("parse");
        assert_eq!(t.host, "127.0.0.1");
        assert_eq!(t.port, 5432);
        assert_eq!(t.user, "tama");
        assert_eq!(t.password, None);
        assert_eq!(t.database, "tama");
        assert_eq!(t.query, "");
        assert_eq!(
            t.dsn("secret"),
            "postgres://tama:secret@127.0.0.1:5432/tama"
        );
    }

    #[test]
    fn test_parse_db_url_default_port() {
        let t = parse_db_url("postgresql://u:p@h/db").expect("parse");
        assert_eq!(t.port, 5432);
        assert_eq!(t.password.as_deref(), Some("p"));
    }

    #[test]
    fn test_parse_db_url_rejects_bad_scheme() {
        assert!(parse_db_url("mysql://u@h/db").is_err());
    }

    #[test]
    fn test_parse_db_url_rejects_missing_db() {
        assert!(parse_db_url("postgres://u@h").is_err());
    }
}
