on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI__API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI__KEY: ${{ secrets.OPENAI_KEY }}
          config.model: ${{ secrets.MODEL_NAME }}
          config.fallback_models: '${{ secrets.MODEL_NAME }}'
          config.custom_model_max_tokens: "256000"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "false"
