[package]
name = "tama-web"
version = "1.56.0"
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
# SSR-only deps
axum = { workspace = true }
axum-server = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
include_dir = { workspace = true }
reqwest = { workspace = true }
mime_guess = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-stream = { version = "0.3" }
futures-util.workspace = true
uuid = { version = "1", features = ["v4"] }
tempfile = { workspace = true }
chrono = "0.4.44"
tama-core = { path = "../tama-core", features = ["web-ui"] }
toml = { workspace = true }
thiserror = { workspace = true }
nix = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-gen = { version = "5" }

[[test]]
name = "server_test"
path = "tests/server_test.rs"

[[test]]
name = "config_structured_test"
path = "tests/config_structured_test.rs"

[[test]]
name = "downloads_api"
path = "tests/downloads_api.rs"

[dev-dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
tempfile = { workspace = true }
tower = { version = "0.5", features = ["util"] }
